### ISSUE TITLE
Can't place order with Klarna selected as payment method.

### ISSUE THREAD

**Issue by vlaskiz** [woocommerce/woocommerce-gateway-klarna#114]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior
Complete checkout once social number is entered.
-

### Actual behavior
WooCommerce throws an error:
Expected field to be an integer: pclass (Error code: 0)

02-04-2018 @ 17:42:41 - Klarna API error: InvalidArgumentException::__set_state(array(
   'message' => 'Expected field to be an integer: pclass',
   'string' => '',
   'code' => 0,
   'file' => '/home/.../.../public_html/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/php-xmlrpc/src/Klarna/XMLRPC/Klarna.php',
   'line' => 2905,
   'trace' => 
  array (
    0 => 
    array (
      'file' => '/home/.../.../public_html/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/php-xmlrpc/src/Klarna/XMLRPC/Klarna.php',
      'line' => 1529,
      'function' => 'checkInt',
      'class' => 'Klarna\\XMLRPC\\Klarna',
      'type' => '->',
      'args' => 
      array (
        0 => '',
        1 => 'pclass',
      ),
    ),
    1 => 
    array (
      'file' => '/home/.../.../public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-invoice.php',
      'line' => 665,
      'function' => 'reserveAmount',
      'class' => 'Klarna\\XMLRPC\\Klarna',
      'type' => '->',
      'args' => 
      array (
        0 => '1003912082',
        1 => '',
        2 => -1,
        3 => 0,
        4 => '',
      ),
    ),

-

### Steps to reproduce the behavior
The usual checkout flow
-

### Klarna plugin version
2.5.6
-

### WordPress version
4.9.2
-

### WooCommerce version
3.2.6
-

### Klarna country

-

**Comment by NiklasHogefjord** [comment]
The response indicates that there is something wrong with you account at Klarna (pclass issue). Make sure that you are using an Eid for Klarna part payment (KPM).

If the problem remains, please send a support ticket to support@krokedil.se.
