### ISSUE TITLE
Update Guzzle to latest version

### ISSUE THREAD

**Issue by davdebcom** [woocommerce/woocommerce-gateway-klarna#127]
Hi @NiklasHogefjord 

How have you been since Lisbon? :)

We are getting reports of conflicts between the Klarna plugin and our Mollie plugin, because we use Guzzle 6.3.3 and you use Guzzle 5.3.1. Would you consider updating Guzzle in the Klarna plugin?

Kind regards
David

**Comment by vlaskiz** [comment]
Bumping this up, as it breaks the website when using both plugins.

**Comment by NiklasHogefjord** [comment]
Hi @davdebcom,
Sorry for the late reply. I'm on vacation at the moment so our response time are a bit longer than usual.

It was great to meet you in Lisbon. It would be really interesting to chat again soon! :)

When it comes to the actual issue with the Guzzle library, that is a part of Klarnas SDK. The SDK is not something that we maintain ourselves.

However, this plugin is on its way to be retired. Instead we have a new plugin for Klarna Checkouts new platform v3. The new plugin is available here: https://wordpress.org/plugins/klarna-checkout-for-woocommerce/.

A transition guide is available here: https://docs.woocommerce.com/document/moving-v2-v3-klarna/.

I would suggest to move over to the new plugin instead. That plugin doesn't use Guzzle. Instead it uses wp_remote_request() to communicate with Klarnas rest API.

**Comment by davdebcom** [comment]
Thank you, I'll inform the users!
