### ISSUE TITLE
UK and US missing from description in readme.txt

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-klarna#132]
Klarna works in Sweden, Denmark, Finland, Norway, Germany, Austria, the Netherlands, UK and United States

**Comment by NiklasHogefjord** [comment]
Hi @allendav,
This is an old plugin that is about to be retired. 

We recommend you to use this plugin instead: https://github.com/krokedil/klarna-checkout-for-woocommerce (https://wordpress.org/plugins/klarna-checkout-for-woocommerce/).
