### ISSUE TITLE
Klarna Order Management - Klarna Environment - Playground

### ISSUE THREAD

**Issue by thebeautystore** [woocommerce/woocommerce-gateway-klarna#133]
When viewing an order made via klarna on our live site, I am seeing the following under the klarna order management tab

Klarna Environment: Playground
Klarna order status: AUTHORIZED
Initial Payment method: Pay later

I am using live credentials, we are not in test mode and the orders are being captured on the live klarna portal.

I have also checked our klarna playground environment and there is no orders.

**Comment by NiklasHogefjord** [comment]
This repository is for a plugin that is no longer being updated. Looking at what you see in the WooCommerce order I think your question belongs in this repository: https://github.com/krokedil/klarna-order-management-for-woocommerce.

However, I don't think that this is a general issue in the plugin. I suggest that you submit a support ticket to support@krokedil.com instead and we can help you further.
