### ISSUE TITLE
Points not deducted with WooCommerce Points and Rewards

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-klarna#45]
### Expected behavior

When checking out with Klarna using points from WooCommerce Points and Rewards, points should be redeemed and deducted from the the customer account.  

**Order example using Stripe:**

![](http://cld.wthms.co/1fBJb/k1dTUytq+)

**Points Log Example using Stripe:**

![](http://cld.wthms.co/1ege5/2br5tMom+)
### Actual behavior

The checkout totals when using Klarna Checkout and WooCommerce Points and Rewards are fine.  The customer pays the correct amount.  But, points are not removed from the account:

**Order Example using Klarna Checkout:**

![](http://cld.wthms.co/wYCD/3MzdIYql+)

**Nothing logged in the Points Log**
### Steps to reproduce the behavior
- Add some points to a user account using WooCommerce Points and Rewards
- Use some points toward the purchase on the cart page
- Checkout with Klarna Checkout
- Review the order and Points Log to see that points aren't deducted
### Klarna version
- Latest
### WordPress version
- Latest
### WooCommerce version
- Latest
### Klarna country
- Sweden

I think this is possibly due the custom Checkout and Thank You page used in Klarna.  Points and Rewards hooks into the `woocommerce_checkout_order_processed` action to reduce points.

@slobodan

**Comment by slobodan** [comment]
Responded in Zendesk, Klarna Checkout doesn't officially support Points and Rewards.

**Comment by Pituca** [comment]
Hi,

I'm using Woocommerce Points and Rewards and I have the same issue, however I not using any electronic payment that might suggest any incompatibility. Im using WordPress 4.7 with woocommerce 2.6.11 (latest) and mixture 1.3.9 (latest). If anyone else find the solution please sharing it with us will be much appreciated.

**Comment by prezadoshift** [comment]
No one has a solution to this problem?
I have the same issue, I'm not using electronic payment as well... Im using WP 4.9.4, woocommerce 3.3.3 (latest) and Points & Rewards 1.5.14
