### ISSUE TITLE
Checkout jumps over order review on mobile

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-klarna#50]
On mobile, Klarna checkout jumps over the order review section needed for adjusting quantities and choosing shipping options.  While the jump to pay button streamlines checkout, it may not be the best experience.  What do you think? 

@slobodan

**Comment by slobodan** [comment]
@mdmoore if you change the order of shortcodes in the page, everything should be fine:

You probably have [woocommerce_klarna_checkout] first, followed by [woocommerce_klarna_checkout_widget]. Works fine in my test environment, don't see any reason why it would be broken. 

If this was the problem and it works for you after the change, can you please close the issue?

**Comment by hannahswain** [comment]
@slobodan I was able to reproduce this issue on my own test site with only the `[woocommerce_klarna_checkout]` shortcode on the page.  When loading on a mobile device, the cursor is automatically set to the `Your Details` field.

**Comment by slobodan** [comment]
@hannahswain thanks for clarifying the issue, I misunderstood @mdmoore sorry.

This is how Klarna Checkout works by default, and I do agree it can make it a bit weird on mobile.

There's parameter that can be sent to Klarna to disable it when creating the Klarna Checkout object, it's currently possible to use a filter that our plugin has (`kco_create_order`, add `$create['gui']['options'] = array( 'disable_autofocus' )` to it) to do it, but I will make autofocus disabled by default in next version of our plugin.

Thank you both for suggesting this, great idea.

**Comment by hannahswain** [comment]
@slobodan Awesome, thanks! I'll pass this on to the customer in question.

**Comment by slobodan** [comment]
@hannahswain 👍 

Keep in mind that if they need it fixed right away, it's pretty easy to do it too. Just in case they don't want to wait for new version to be out.

**Comment by slobodan** [comment]
Fixed in 2.2.3
