### ISSUE TITLE
Custom fields for checkout

### ISSUE THREAD

**Issue by JKetelaar** [woocommerce/woocommerce-gateway-klarna#53]
I'm trying to achieve a way to integrate custom fields with the checkout process.
As of now it's not possible to have a custom field for the house number or suffix, as this is done by splitting the value from the address into street, number and suffix.

Just to be sure, there's no way to do this right?
If so, would you guys accept a pull request if I would create a filter for the house number and suffix?

**Comment by slobodan** [comment]
Yes, please submit your PR to develop branch of our fork of WooCommerce's repo and we'll take a look at it. Thank you!

https://github.com/krokedil/woocommerce-gateway-klarna/tree/develop
