### ISSUE TITLE
Conflict with min/max plugin on iPad using Safari

### ISSUE THREAD

**Issue by zandyring** [woocommerce/woocommerce-gateway-klarna#62]
### Expected behavior

When min/max plugin and Klarna are both enabled on any site, in any browser, on any OS, I would expect that the max quantity is respected.

-

### Actual behavior

Using Safari (only) on iPad (only), you can bypass the max amount restriction, by updating the amount in the cart.

Test site:
![img_0023](https://cloud.githubusercontent.com/assets/7304712/22897648/7b4fc1a6-f1f2-11e6-9ee4-34cdb11090da.PNG)
![img_0026](https://cloud.githubusercontent.com/assets/7304712/22897787/039ebd8c-f1f3-11e6-90a1-bdc2bed72d46.PNG)

Demo on user's site:
http://cld.wthms.co/l7bt/wSCaAJzR

-

### Steps to reproduce the behavior

0. Enable Klarna and Min/Max plugins
1. Set up product with a maximum amount (5x)
2. Navigate to site on an iPad using Safari
3. Add the maximum number of that product to your cart (5x)
4. Go to your cart
5. Add additional units (7x)
6. See error that you can only add 5x (in this example)
7. Do not click "update cart"
8. Click on Checkout
9. In Klarna checkout, see your total krona update to the new (7x) quantity amount.

-

### WordPress version

WordPress 4.7.2
-

### WooCommerce version

WooCommerce 2.6.14
-

### Klarna country

Sweden
-

**Comment by spraveenitpro** [comment]
Hi @NiklasHogefjord , Just wanted to check with you on this issue, thanks

**Comment by slobodan** [comment]
@zandyring which min/max plugin?

**Comment by zandyring** [comment]
@slobodan - it is this Min/Max plugin: https://woocommerce.com/products/minmax-quantities/

Sorry about getting the repo wrong :( 
I'll get it right next time.

**Comment by slobodan** [comment]
@zandyring thanks. And no worries about the repo at all, you're not supposed to know that :) Just letting you know for any further issues.

**Comment by zandyring** [comment]
@slobodan any update or timeline on this?

**Comment by slobodan** [comment]
@zandyring we'll work on this for next release, but no immediate timeline, sorry.

Moved the issue to out repo: https://github.com/krokedil/woocommerce-gateway-klarna/issues/45

**Comment by slobodan** [comment]
@zandyring, can you please email me min/max plugin to slobodan@krokedil.se?

**Comment by slobodan** [comment]
@zandyring I fixed the issue in our develop branch, the fix will be included in next release, but if you want to have access to it right away, you can get it here:

https://github.com/krokedil/woocommerce-gateway-klarna/tree/develop

The fix adds woocommerce_check_cart_items hook to Klarna Checkout page, and if there are any issues found, redirects to Cart page.

However, seems like this is a bigger issue, on iPad when I try to exceed max allowed quantity for an item in cart page, I do get the error, header cart widget in Storefront theme does show the updated (not allowed) quantity. Haven't checked in more detail than this, but it might be worth looking into.
