### ISSUE TITLE
PHP Warnings on WooCommerce 3.0

### ISSUE THREAD

**Issue by joonasvanhatapio** [woocommerce/woocommerce-gateway-klarna#74]
PHP errors filling up on every purchase.  Not preventing purchases, only warning message in WooCommerce 3

2017/05/05 17:09:28 [error] 3772#3772: *264778 FastCGI sent in stderr: "PHP message: country was called incorrectly. Customer properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->update_session, WC_Cart->calculate_totals, WC_Cart->calculate_fees, do_action('woocommerce_cart_calculate_fees'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Gateway_Klarna_Invoice_Extra->calculate_fees, WooCommerce->__get, WooCommerce->payment_gateways, WC_Payment_Gateways::instance, WC_Payment_Gateways->__construct, WC_Payment_Gateways->init, WC_Gateway_Klarna_Part_Payment->__construct, WC_Gateway_Klarna_Helper->get_account_icon, WC_Legacy_Customer->__get, wc_doing_it_wrong. This message was added in version 3.0.
PHP message: country was called incorrectly. Customer properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->update_session, WC_Cart->calculate_totals, WC_Cart->calculate_fees, do_action('woocommerce_cart_calculate_fees'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Gateway_Klarna_Invoice_Extra->calculate_fees, WooCommerce->__get, WooCommerce->payment_gateways, WC_Payment_Gateways::instance, WC_Payment_Gateways->__construct, WC_Payment_Gateways->init, WC_Gateway_Klarna_Part_Payment->__construct, WC_Gateway_Klarna_Helper->get_account_icon, WC_Gateway_Klarna_Helper->get_eid, WC_Legacy_Customer->__get, wc_doing_it_wrong. This message was added in version 3.0.
PHP message: country was called incorrectly.

### Klarna plugin version

-  2.3.6

### WordPress version

- 4.7.4

### WooCommerce version

- 3.0.5

### Klarna country

- Finland

**Comment by jonasostrom** [comment]
Any updates on this?

**Comment by derpoho** [comment]
Anybody alive? We need this fixed ;)

**Comment by zamson** [comment]
I'm getting loads of these errors as well. Any ETA on a fix?

**Comment by slobodan** [comment]
They are all fixed in develop branch at our repo. The plan is to release it next week.

Sorry you waited for so long, but please create all future issues in our repo instead, as issue template in this repo states.
