### ISSUE TITLE
no "new order" email notification

### ISSUE THREAD

**Issue by Tobias-Conrad** [woocommerce/woocommerce-gateway-klarna#82]
different question; @niklaswallerstedt do you as an admin get a "new order" email notification from woocommerce when you bill the customer via klarna? i have this issue.

`
### WordPress Environment ###

Home URL: https://www.santegra-international.com
Site URL: https://www.santegra-international.com
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 7.0.18
PHP Post Max Size: 100 MB
PHP Time Limit: 1200
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: san_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

Advanced Database Cleaner: von Younes JFR. – 2.0.1
Antispam Bee: von pluginkollektiv – 2.7.1
BackupBuddy: von iThemes – 7.3.1.8
Bring Back the Get Shortlink Button: von Thorsten Frommen – 1.1.0
Wordpress Comments List Building: von Tobias B. Conrad – 4.1.0
Duplicate Post: von Enrico Battocchi – 3.2
Easy FancyBox - Pro extension: von RavanH – 1.5.3
Easy FancyBox: von RavanH – 1.6
Easy Theme and Plugin Upgrades: von Chris Jean – 2.0.0
Email Tracker: von Prashant Baldha – 1.3
Envato Market: von Derek Herman – 1.0.0-RC2
Idea Factory: von Nick Haskins – 1.2
IgniteWoo Updater: von IgniteWoo.com – 2.1.11
kk Star Ratings: von Kamal Khan – 2.5.1
Language Fallback: von Bernhard Kau – 1.0.3
Notely: von Michael Ott – 1.3
WooCommerce Product Filter: von Mihajlovic Nenad – 6.2.3
Pretty Link Pro: von Blair Williams – 2.0.9
Redirect Post to URL: von Stefan Böttcher – 1.0
Redirect to URL: von Marcel Fagas – 1.1.2
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
SearchWP Exclude UI: von Jonathan Christopher – 1.0.1
SearchWP Fuzzy Matches: von SearchWP
LLC – 1.4.3

SearchWP LIKE Terms: von Jonathan Christopher – 2.4.4.1
SearchWP German Stemmer: von Jonathan Christopher – 1.0.1
SearchWP Term Highlight: von Jonathan Christopher – 2.1.5
SearchWP Term Synonyms: von SearchWP
LLC – 2.4.11

SearchWP Xpdf Integration: von Jonathan Christopher – 1.1.1
SearchWP: von SearchWP
LLC – 2.8.9

Simple Tooltips: von Justin Saad – 2.1.3
SEO by SQUIRRLY: von Squirrly SEO – 8.0.2
Stream: von XWP – 3.2.0
Tawk.to Live Chat: von Tawkto – 0.2.9
Timed Content: von K. Tough – 2.6
TinyMCE Advanced: von Andrew Ozz – 4.5.6
Vendidero Helper: von Vendidero – 1.1.3
WooCommerce Cart Reports: von WooCommerce – 1.1.15
WooCommerce Checkout Field Editor Pro: von ThemeHiGH – 2.5.3
WooCommerce Klarna Gateway: von WooCommerce – 2.3.10
WooCommerce Germanized Pro: von Vendidero – 1.7.7
WooCommerce Germanized: von Vendidero – 1.8.11
WooCommerce Google Analytics Pro: von SkyVerge – 1.3.4
WooCommerce Sequential Order Numbers Pro: von SkyVerge – 1.11.2
WooCommerce Shipment Tracking: von WooCommerce not updated since no nice changes – 1.6.8
WooCommerce URL Coupons: von SkyVerge – 2.5.1
WooCommerce: von Automattic – 3.0.8
WooCommerce Helper: von WooCommerce – 1.7.2 – Netzwerk aktiviert
WP-Optimize: von David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

Wordpress Rankie: von Atef – 1.6.2
WP SEO Structured Data Schema: von kcseopro – 2.0
WP Sitemap Page: von Tony Archambeau – 1.6
WooCommerce & WP Email Marketing Integration: von Tobias B. Conrad – 3.7.1
YITH WooCommerce Wunschliste: von YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #1013 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /checkout/
Mein Konto: #9 - /mein-konto/

### Theme ###

Name: Flatsome Child
Version: 3.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome-child/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: Eid not set Secret key not set Checkout URL not set
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: ✔
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`

**Comment by niklaswallerstedt** [comment]
@Tobias-Conrad I'm not on the new order email list, but I can try it later today with a test order.

**Comment by niklaswallerstedt** [comment]
@Tobias-Conrad I do receive the new order email.

**Comment by smyth64** [comment]
I have the same problem =/ When somebody orders with another payment method (PayPal for example) I as an admin receive the notification e-mail. 

If somebody orders with Klarna, I don't get the email but the customer receives the email.

**Comment by NiklasHogefjord** [comment]
I'm closing this issue. @smyth64 - the main repository used for this plugin can be found here: https://github.com/krokedil/woocommerce-gateway-klarna.

If you are certain that this is a bug in the Klarna plugin you are welcome to open an issue in the main repository. Otherwise you are welcome to get in touch with our support at support@krokedil.com.
