### ISSUE TITLE
Warnings on thank you page (Order properties)

### ISSUE THREAD

**Issue by michaelrimbach** [woocommerce/woocommerce-gateway-klarna#84]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- No warnings

### Actual behavior

- On the "thank you" page you will get notices like this:

   payment_method wurde fehlerhaft aufgerufen. Order properties should not be accessed directly. Backtrace: require('C:\xampp704\htdocs\xyz\wp-blog-header.php'), require_once('C:\xampp704\htdocs\xyz\wp-includes\template-loader.php'), include('C:\xampp704\htdocs\xyz\wp-content\themes\storefront\page.php'), get_template_part, locate_template, load_template, require('C:\xampp704\htdocs\xyz\wp-content\themes\storefront\content-page.php'), do_action('storefront_page'), WP_Hook->do_action, WP_Hook->apply_filters, storefront_page_content, the_content, apply_filters('the_content'), WP_Hook->apply_filters, fixShortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::order_received, wc_get_template, include('C:\xampp704\htdocs\xyz\wp-content\plugins\woocommerce\templates\checkout\thankyou.php'), apply_filters('woocommerce_thankyou_order_received_text'), WP_Hook->apply_filters, WC_Gateway_Klarna_Part_Payment->output_klarna_details_confirmation, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 3.0 hinzugefügt.)

payment_method wurde fehlerhaft aufgerufen. Order properties should not be accessed directly. Backtrace: require('C:\xampp704\htdocs\xyz\wp-blog-header.php'), require_once('C:\xampp704\htdocs\xyz\wp-includes\template-loader.php'), include('C:\xampp704\htdocs\xyz\wp-content\themes\storefront\page.php'), get_template_part, locate_template, load_template, require('C:\xampp704\htdocs\xyz\wp-content\themes\storefront\content-page.php'), do_action('storefront_page'), WP_Hook->do_action, WP_Hook->apply_filters, storefront_page_content, the_content, apply_filters('the_content'), WP_Hook->apply_filters, fixShortcode, do_shortcode, preg_replace_callback, do_shortcode_tag, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::order_received, wc_get_template, include('C:\xampp704\htdocs\xyz\wp-content\plugins\woocommerce\templates\checkout\thankyou.php'), apply_filters('woocommerce_thankyou_order_received_text'), WP_Hook->apply_filters, WC_Gateway_Klarna_Invoice->output_klarna_details_confirmation, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Weitere Informationen: Debugging in WordPress (engl.) (Diese Meldung wurde in Version 3.0 hinzugefügt.)

You could fix it when you change $order->payment_method to $order->get_payment_method() at output_klarna_details_confirmation and output_klarna_details_confirmation_email (invoice and part-payment file). This is only a WC 3 fix. 

### Steps to reproduce the behavior

- Turn debug mode on and go to the "thank you" page.

### Klarna plugin version

- 2.3.11

### WordPress version

- 4.7.5

### WooCommerce version

- 3.0.7

### Klarna country

- DE (Germany)

**Comment by michaelrimbach** [comment]
Any news here?

**Comment by NiklasHogefjord** [comment]
Update to the latest version (v2.5.2 will be released during the day) and see if the notices are removed.

I'm closing this issue now. If you want to re open it, please submit an issue in this repo instead: https://github.com/krokedil/woocommerce-gateway-klarna
