### ISSUE TITLE
WC_Order_Item_Meta deprecated

### ISSUE THREAD

**Issue by jarle0db** [woocommerce/woocommerce-gateway-klarna#92]
Getting PHP notices for the use of WC_Order_Item_Meta in Klarna version 2.4.1 and WooCommerce 3.1.2

Happens in:
woocommerce-gateway-klarna/classes/class-klarna-order.php
woocommerce-gateway-klarna/classes/class-klarna-checkout.php

**Comment by slobodan** [comment]
Thanks for reporting this @jarle0db 

Fixed it in develop branch, will include it with next release.

**Comment by slobodan** [comment]
Also, please use krokedil/woocommerce-gateway-klarna for future issues.
